# Functions and Object Oriented Programming

This notebook will introduce a few more python concepts that are slightly more complex. The first of those topics is *functions*. Functions can be used to automate repetitive tasks and avoid copying code blocks. All functions begin with a definition syntax. In python the syntax is:

In [1]:
def function(input1, input2, input3=optional):

IndentationError: expected an indented block (Temp/ipykernel_6756/2594476373.py, line 1)

the __def__ keyword is used before the name of the function and it signals to python that the remaining code will correspond to a function definition. The name of the function is __function__ and it has 3 inputs. input1 and input2 are required each time the function is called, but input3 isn't. To create optional function arguments, the '=' sign must be used and the default argument for that input follows the '=' sign. 

To illustrate function definition, I'll create a function called *multiply* that multiplies two required arguments given to it and prints a message if I set the third input variable to True

In [7]:
def multiply(arg1, arg2, verbose=False):
    if verbose is True:
        print('the product is', arg1*arg2)
    return arg1 * arg2

Notice I've introduced a few more key terms. The <span style="color:green"> return </span> keyword is used to tell python what value the function needs to return when it's called. So, in the case above, *multiply* returns the product of arg1 and arg2. While many functions return a value, they don't need to. The function does not need a <span style="color:green"> return </span> keyword to be correct. To break back out of the function definition into regular code, just end the indentation.

Now that we have defined the _multiply_ function above, the function is stored in memory and can be used below. To use a function, call its name with parenthesis and inputs.

In [4]:
multiply(10,20)

200

The function was called above, but the value it returned wasn't stored in any variable. To store the return value from the function, simply put a variable and '=' sign in front of the function call.

In [9]:
product = multiply(10,20)
print(product)

200


If we want to use the optional argument _verbose_, we can do so by using an '=' sign in the function call.

In [8]:
product = multiply(10, 20, verbose=True)

the product is 200


By specifying _verbose = True_, that optional variable is set to true and the function prints the conditional string. Functions are useful because they allow one to write one piece of code and deploy it multiple times across different scripts. I can deploy the above function in a for loop to calculate a set of products.

In [10]:
numbers_list = [1, 2, 3, 4, 5, 6]

for number in numbers_list:
    product = multiply(number,number)
    print(product)

1
4
9
16
25
36


### Practice 

Your turn to build a function. Make a function that takes a string as an input and returns a list of the indidivual words in the string. I recommend looking [here](https://www.w3schools.com/jsref/jsref_split.asp#:~:text=The%20split()%20method%20splits,string%20is%20split%20between%20words.) for help on doing this string manipulation.

## Object Oriented Programming (OOP)

This subject is quite large and starts to incorporate some complex topics like memory efficiency and class structure. If you want to learn more about object oriented programming, I'd recommend taking an online course. In this tutorial, we're just going to learn enough object oriented programming to know how to use it for our purposes.

### classes

You can think of classes as special objects in python that contain unique information and operations. This concept is quite hard to understand without coding it yourself, so no worries if it doesn't make sense from a description. 

Let's start by defining a class called __my_class__. The _pass_ syntax is used to prevent python from throwing an error message when we leave that section of code empty.

In [3]:
class my_class:
    pass

Notice that, unlike a function, the class doesn't have any arguments. You can technically pass arguments directly to the class using something called a _constructor_, but that won't be covered here.

Now that we've defined our class, we need to _instantiate_ it, which basically just means we need to call the class. To call __my_class__, we can use this syntax:

In [15]:
my_class_instance = my_class()
print(type(my_class_instance))

<class '__main__.my_class'>


the __my_class_instance__ variable is called an _instance_, because it contains the instantiated version of the class. We can instantiate this class multiple times and create many different instances:

In [16]:
instance_1 = my_class()
instance_2 = my_class()
instance_3 = my_class()

Each of these instances are separate in the sense that operations performed on instance_1, wont affect the other instances. Classes must be instantiated before they can be used to store data and perform manipulations.

#### Attributes

Classes store data in the form of class _attributes_. These attributes are are named variables stored within the class. For example, I want to store the value 100 in __my_class__ and to do so I am going to store it in the variable __my_number__

In [17]:
my_class_instance.my_number = 100

Notice the strange syntax. The "." symbol is used to call one of the attributes associated with __my_class__. This is the general structure for accessing data and performing operations on classes in python.

Now, if I want to access the class attribute I just stored, I can do so in a similar manner.

In [18]:
print(my_class_instance.my_number)

100


#### Methods

Classes also have operations associated with them that can be used to process data stored within the class. These operations are called _methods_. Class methods look similar to attributes, but they act like functions.

Below, I am going to define a class attribute that takes the my_number variable associated with the class and combines it with another input string, and then prints it. It is best practice to define the class with all of its methods at once.

In [20]:
class my_class:
    def __init__(self): #this function is the constructor. It can be ignored
        pass
    
    def number_combine(self, input_string): #the self variables is necessary if accessing class attributes
        print(input_string, self.my_number)



instance = my_class() #instantiate the class
instance.my_number = 100 #store this number in the class attribute my_number
input_string = 'my favorite number is ' 
instance.number_combine(input_string) #call the class method number_combine on the instance of my_class

my favorite number is  100


You'll notice above that the keyword _self_ is used in the number_combine method. The _self_ keyword tells python that this method has access to the methods and attributes associated with my_class. So, since I need the my_number attribute, I must include _self_ as an input to the number_combine method to be able to access the class attributes.

## Using Classes in our Research

If the above topics are confusing, that's okay. Because, for the most part, you won't need to be able to write your own classes to be successful in the group, you just need to know how to use them. To understand how to use them, we're going to take a look at __numpy__. Start by importing Numpy

In [27]:
import numpy as np

When we import numpy, what is actually happening? What we're doing is calling a script stored in our environment that contains a ton of functions and classes. The most important class (and data type) in numpy is the _array_. Arrays must be instantiated with some type of argument. Arrays are essentially the same as the matrix data type in Matlab, so let's feed our array a vector to instantiate it.

In [28]:
array = np.array([0,1,2,3])
print(array)

[0 1 2 3]


We can see that the array() class from numpy took our list and turned it into a 1D array. Arrays are often used in scientific scripting because they are much faster and already have a bunch of built-in linear algebra operations.

In [30]:
det_array = np.array([[1,2],[3,4]])
determinant = np.linalg.det(det_array)
print(determinant)

-2.0000000000000004


In the above example, we used a numpy function to manipulate the _array_ class from numpy. Arrays are not necessarily interchangeable with the native data types in Python, so passing an array to other functions might break. Now let's look at some methods and attributes of the _array_ class.

In [38]:
np.random.seed(100) #doing this so we get the same result each time
rand_array = np.random.rand(5,5) #creating a random array 
print(rand_array)

[[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886]
 [0.12156912 0.67074908 0.82585276 0.13670659 0.57509333]
 [0.89132195 0.20920212 0.18532822 0.10837689 0.21969749]
 [0.97862378 0.81168315 0.17194101 0.81622475 0.27407375]
 [0.43170418 0.94002982 0.81764938 0.33611195 0.17541045]]


In [39]:
shape = rand_array.shape
print(shape)

(5, 5)


In [42]:
new_array = rand_array.ravel()
print(new_array)

[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886 0.12156912
 0.67074908 0.82585276 0.13670659 0.57509333 0.89132195 0.20920212
 0.18532822 0.10837689 0.21969749 0.97862378 0.81168315 0.17194101
 0.81622475 0.27407375 0.43170418 0.94002982 0.81764938 0.33611195
 0.17541045]


As you can see, the _shape_ attribute returns the shape of the array, which is 5x5 in this case. The _ravel_ method flattens the array into a 1D array. 

To summarize, you have instantiated the array class by inputting a python list to it, and then used a built-in numpy function to get its determinant. After doing that, you instantiated another array, and used its class attributes and methods to get back its shape and perform operations on it.

### Practice

Now, using the internet and [numpy documentation](https://numpy.org/doc/stable/user/basics.creation.html), instantiate an array object without directly passing a python list to it (similar to how I did using the random package). Then, find the eigenvalues of the array and use those eigenvalues to make a diaganol array, with the eigenvalues on the diaganol.